### ISSUE TITLE
Usage of KBDFans logo in forks

### ISSUE THREAD

**Issue by jakobkg** [kb-elmo/67mk_E#1]
Hi! Great work on this circuit design, an open source kbd67 pcb is precisely what I've been looking for to add to my own 65% project.

I'd like to fork this design and make some modifications, but I find myself unsure about the inclusion of the KBDfans logo in my fork as I couldn't see anything about the logo, its trademark or usage guidelines in the readme or license. Is the logo just there to indicate that this design is compatible with certain KBDfans products, meaning I should keep it in my fork given I don't break that compatibility, or is this design somehow affiliated with KBDfans meaning I should remove the logo from my fork as neither I nor my project have anything to do with KBDfans directly?

Thanks!

**Comment by kb-elmo** [comment]
The KBDfans logo is indeed a trademark and it was added to this PCB in mutual agreement with the KBDfans owner (even though the project was not a commission or in any way sponsored by them).  
They agreed to this since I do not plan to sell this PCB commercially.

If you are planning to use the PCB for a different keyboard it would be best if you removed it.  
A note in the project notes saying that the PCB is still compatible with the 67lite would be sufficient I think.

**Comment by jakobkg** [comment]
Thank you, I'll remove the logo from my fork and replace it with something else or just leave your icon by itself.

**Comment by kb-elmo** [comment]
Are you planning to use this PCB for a commercially sold product?

If yes it would be best to remove the Elmo logo as well since it's technically not my logo and is trademarked by the Sesame Street 😄 
I only use this for my personal projects that I do not intend to sell.
Putting it on a commercial product could result in trademark issues.

**Comment by jakobkg** [comment]
I will not be putting this into a commercial product! I'm making a stacked acrylic gasket mounted 65% board intended as a beginners' board, as I find the typical tray mounted beginners' kits to be kind of lacking and want to provide what I hope to be a cheaper and "better" alternative to anyone willing to tinker. If you prefer I could remove the icon and keep credit as a text in silkscreen and the readme of my fork, in case you don't want to be affiliated with my messy trace routing 😄

**Comment by jakobkg** [comment]
I'll replace the logos with something of my own and keep credit to a "Based on a design by kb-elmo" type text in silkscreen and documentation, then! I'll make sure to tag or somehow notify you so you can see the final thing and let me know if the credit is alright when it's done
